name: Code Testing
 
on: workflow_dispatch
 
jobs:
  say_hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello!
        run: echo "Helloooooooo Cyber* "
 
  python-tests:
    name: Testing Python
    needs: say_hello
    strategy: 
      matrix:
        os: [ ubuntu-24.04, ubuntu-22.04, ubunut-20.04, macos-13 ]
        python-version: [ 3.11.0, 3.10.15, 3.8.12 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Checks Python version
        run: python --version
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyton-version }}
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
      - name: Run tests
        run: |
          pytest
 
 
  work_done:
      runs-on: ubuntu-24.04
      needs: python-tests
      if: always()
      steps:
        - name: Done!
          run: echo "👏 Matrix workflow completed successfully!"
