name: Code Testing
 
on: workflow_dispatch
 
jobs:
  say_hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello!
        run: echo "Helloooooooo Cyber* "
 
  python-tests11:
    name: Testing Python v3.11
    needs: say_hello
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Checks Python version
        run: python --version
 
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
      - name: Run tests
        run: |
          pytest
 
 
  work_done:
      runs-on: ubuntu-24.04
      needs: python-tests11
      if: always()
      steps:
        - name: Done!
          run: echo "👏 Matrix workflow completed successfully!"
